### ISSUE TITLE
Error during make all

### ISSUE THREAD

**Issue by Gkandoi** [maxhwardg/advanced_multiloops#1]
Hi

I'm trying to install this on a Windows machine with Cygwin. The *cmake* command runs fine, but I get the attached error during the *make all* command:

The cygwin packages have the following versions:\
cmake: 3.6.2
gcc (GCC): 6.3.0
g++ (GCC): 6.3.0
c++ (GCC): 6.3.0

Thanks
[make_all_Error.txt](https://github.com/maxhwardg/advanced_multiloops/files/1078202/make_all_Error.txt)

**Comment by Gkandoi** [comment]
Seems like a Windows/Cygwin problem. I tried installing it on a Ubuntu VM on Windows and it worked.

**Comment by maxhwardg** [comment]
I tried building on Ubuntu 16.04 using those versions of cmake and g++, and I could not reproduce the error. As such, I agree that this might be Cygwin specific

It appears as though the compiler thinks _C is a numeric constant. I can (almost) reproduce the error if I do something like "#define _C 42". I get  the same error plus the usual note saying that error happened during macro expansion. Is it possible something like this is happening on your system?

Perhaps try editing the code slightly to use something other than _C, (it should be straightforward) and see if that fixes the compile error. I would be interested to see if that fixes it.

Edit: It looks like Cygwin has a "#define _C  040" in their version of ctype.h (https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=blob;f=newlib/libc/include/ctype.h). I believe this explains the compile error. I would call this a bug in Cygwin. If you need to use Cygwin, simply change _C to something else in aalberts_model.cpp and it should compile, in theory.
